version = 1

[[annotations]]
path = [
  ".envrc",
  ".github/**/",
  ".gitignore",
  "README.md",
  "flake.lock",
  "flake.nix",
  "Cargo.lock",
  "Cargo.toml",
  "src/**/",
  "REUSE.toml",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
